### ISSUE TITLE
When running '' python process.py --data_dir ../data/'' , the following two errors occur

### ISSUE THREAD

**Issue by ouhongxu** [CRIPAC-DIG/RHGN#1]
When running '' python process.py --data_dir ../data/'' , the following two errors occur：

Using backend: pytorch
Traceback (most recent call last):
  File "process.py", line 9, in <module>
    from utils import neighbormap, split_char, filter_sample, combination
ImportError: cannot import name 'neighbormap' from 'utils' (E:\PycharmProjects\RHGN\code\utils.py)

Traceback (most recent call last):
  File "E:/PycharmProjects/RHGN/code/tbdata.py", line 10, in <module>
    from parser import get_args
ImportError: cannot import name 'get_args' from 'parser' (unknown location)

**Comment by yanqilong3321** [comment]
Hi, The bug was fixed，you can follow the latest README to run the code.
